#include "Input.h"

FCaptureOnMousesDelegate MouseDownDelegate;
FCaptureOnMousesDelegate MouseUpDelegate;
FCaptureOnMousesDelegate MouseMoveDelegate;
FCaptureOnMousesWheelDelegate MouseWheelDelegate;
FCaptureOnLMousesDownlDelegate LMouseDownDelegate;
FCaptureOnLMousesUplDelegate LMouseUpDelegate;